// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type YogaAttendance struct {
	ID       int
	UserID   int64
	LessonID int
	Date     time.Time
}

type YogaAvailableLesson struct {
	ID          int
	Date        time.Time
	Time        time.Time
	Description string
	Max         int
}

type YogaLesson struct {
	ID          int
	Date        time.Time
	Time        time.Time
	Description string
	Max         int
	PollID      pgtype.Int8
}

type YogaMembership struct {
	UserID           int64
	Starts           time.Time
	Ends             time.Time
	Type             int
	LessonsAvaliable int
}

type YogaMigration struct {
	ID    int
	Name  string
	RunOn pgtype.Timestamp
}

type YogaRegisteredUser struct {
	LessonID   int
	Registered []int64
}

type YogaSubscription struct {
	ID     int
	UserID int64
	Starts time.Time
	Ends   time.Time
}

type YogaToken struct {
	ID      pgtype.UUID
	Type    pgtype.Int4
	Created pgtype.Date
	Valid   pgtype.Bool
	UserID  pgtype.Int8
}

type YogaUser struct {
	ID        int64
	Username  pgtype.Text
	Name      string
	Emoji     string
	IsBlocked pgtype.Bool
}
