// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PizdaPaymentMethod string

const (
	PizdaPaymentMethodMIR    PizdaPaymentMethod = "MIR"
	PizdaPaymentMethodBIT    PizdaPaymentMethod = "BIT"
	PizdaPaymentMethodPAYPAL PizdaPaymentMethod = "PAYPAL"
)

func (e *PizdaPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PizdaPaymentMethod(s)
	case string:
		*e = PizdaPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PizdaPaymentMethod: %T", src)
	}
	return nil
}

type NullPizdaPaymentMethod struct {
	PizdaPaymentMethod PizdaPaymentMethod
	Valid              bool // Valid is true if PizdaPaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPizdaPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PizdaPaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PizdaPaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPizdaPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PizdaPaymentMethod), nil
}

type PizdaPayment struct {
	ID           int32
	UserID       int64
	Method       PizdaPaymentMethod
	CreationDate time.Time
	Period       pgtype.Range[pgtype.Date]
}

type PizdaUser struct {
	ID        int64
	Username  string
	FirstName string
	LastName  string
	IsBlocked pgtype.Bool
}
