// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const blockUsers = `-- name: BlockUsers :exec
UPDATE pizda.user SET is_blocked = true WHERE tg_id = ANY($1::bigint[])
`

func (q *Queries) BlockUsers(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, blockUsers, ids)
	return err
}

const getUsers = `-- name: GetUsers :many
SELECT id, tg_id, username, first_name, last_name, is_blocked FROM pizda.user WHERE is_blocked = false
`

func (q *Queries) GetUsers(ctx context.Context) ([]PizdaUser, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PizdaUser
	for rows.Next() {
		var i PizdaUser
		if err := rows.Scan(
			&i.ID,
			&i.TgID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.IsBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersIDs = `-- name: GetUsersIDs :many
SELECT tg_id FROM pizda.user WHERE is_blocked = false
`

func (q *Queries) GetUsersIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUsersIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var tg_id int64
		if err := rows.Scan(&tg_id); err != nil {
			return nil, err
		}
		items = append(items, tg_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO pizda.user (tg_id, username, first_name, last_name) VALUES ($1, $2, $3, $4)
  ON CONFLICT(tg_id) DO UPDATE SET
  username = EXCLUDED.username,
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  is_blocked = false
`

type UpsertUserParams struct {
	TgID      int64
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.TgID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
