// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPayment = `-- name: AddPayment :exec
INSERT INTO pizda.payment (user_id, method) VALUES ($1, $2)
`

type AddPaymentParams struct {
	UserID int64
	Method PizdaPaymentMethod
}

func (q *Queries) AddPayment(ctx context.Context, arg AddPaymentParams) error {
	_, err := q.db.Exec(ctx, addPayment, arg.UserID, arg.Method)
	return err
}

const blockUsers = `-- name: BlockUsers :exec
UPDATE pizda.user SET is_blocked = true WHERE id = ANY($1::bigint[])
`

func (q *Queries) BlockUsers(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, blockUsers, ids)
	return err
}

const extendPaymentByMonth = `-- name: ExtendPaymentByMonth :exec
UPDATE pizda.payment
SET period = daterange(lower(period), (upper(period) + INTERVAL '1 month')::date, '[]')
WHERE id = $1
`

func (q *Queries) ExtendPaymentByMonth(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, extendPaymentByMonth, id)
	return err
}

const findUsersByName = `-- name: FindUsersByName :many
SELECT id, username, first_name, last_name, is_blocked FROM pizda.user WHERE first_name ILIKE '%' || $1::text || '%' OR last_name ILIKE '%' || $1::text || '%' OR username ILIKE '%' || $1::text || '%'
`

func (q *Queries) FindUsersByName(ctx context.Context, name string) ([]PizdaUser, error) {
	rows, err := q.db.Query(ctx, findUsersByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PizdaUser
	for rows.Next() {
		var i PizdaUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.IsBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsEndingSoon = `-- name: GetPaymentsEndingSoon :many
SELECT p.id, p.user_id, p.method, p.creation_date, p.period, p.is_notified, u.id as user_id, u.first_name, u.username
FROM pizda.payment p
JOIN pizda.user u ON p.user_id = u.id
WHERE upper(p.period) - CURRENT_DATE <= 3
  AND upper(p.period) - CURRENT_DATE >= 0
  AND p.is_notified = false
`

type GetPaymentsEndingSoonRow struct {
	ID           int32
	UserID       int64
	Method       PizdaPaymentMethod
	CreationDate time.Time
	Period       pgtype.Range[pgtype.Date]
	IsNotified   pgtype.Bool
	UserID_2     int64
	FirstName    string
	Username     string
}

func (q *Queries) GetPaymentsEndingSoon(ctx context.Context) ([]GetPaymentsEndingSoonRow, error) {
	rows, err := q.db.Query(ctx, getPaymentsEndingSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentsEndingSoonRow
	for rows.Next() {
		var i GetPaymentsEndingSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Method,
			&i.CreationDate,
			&i.Period,
			&i.IsNotified,
			&i.UserID_2,
			&i.FirstName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, first_name, last_name, is_blocked FROM pizda.user WHERE is_blocked = false
`

func (q *Queries) GetUsers(ctx context.Context) ([]PizdaUser, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PizdaUser
	for rows.Next() {
		var i PizdaUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.IsBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersIDs = `-- name: GetUsersIDs :many
SELECT id FROM pizda.user WHERE is_blocked = false
`

func (q *Queries) GetUsersIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUsersIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidPayment = `-- name: GetValidPayment :one
SELECT id, user_id, method, creation_date, period, is_notified FROM pizda.payment WHERE user_id = $1 and period @> NOW()::DATE limit 1
`

func (q *Queries) GetValidPayment(ctx context.Context, userID int64) (PizdaPayment, error) {
	row := q.db.QueryRow(ctx, getValidPayment, userID)
	var i PizdaPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.CreationDate,
		&i.Period,
		&i.IsNotified,
	)
	return i, err
}

const getVideoById = `-- name: GetVideoById :one
SELECT id, file_id, name FROM pizda.file WHERE id=$1
`

func (q *Queries) GetVideoById(ctx context.Context, id int32) (PizdaFile, error) {
	row := q.db.QueryRow(ctx, getVideoById, id)
	var i PizdaFile
	err := row.Scan(&i.ID, &i.FileID, &i.Name)
	return i, err
}

const getVideos = `-- name: GetVideos :many
SELECT id, file_id, name FROM pizda.file order by id
`

func (q *Queries) GetVideos(ctx context.Context) ([]PizdaFile, error) {
	rows, err := q.db.Query(ctx, getVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PizdaFile
	for rows.Next() {
		var i PizdaFile
		if err := rows.Scan(&i.ID, &i.FileID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentAsNotified = `-- name: MarkPaymentAsNotified :exec
UPDATE pizda.payment SET is_notified = true WHERE id = $1
`

func (q *Queries) MarkPaymentAsNotified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markPaymentAsNotified, id)
	return err
}

const updateFileId = `-- name: UpdateFileId :exec
UPDATE pizda.file SET file_id=$1 WHERE id=$2
`

type UpdateFileIdParams struct {
	FileID string
	ID     int32
}

func (q *Queries) UpdateFileId(ctx context.Context, arg UpdateFileIdParams) error {
	_, err := q.db.Exec(ctx, updateFileId, arg.FileID, arg.ID)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO pizda.user (id, username, first_name, last_name) VALUES ($1, $2, $3, $4)
  ON CONFLICT(id) DO UPDATE SET
  username = EXCLUDED.username,
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  is_blocked = false
`

type UpsertUserParams struct {
	ID        int64
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
