// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OnlineSubscription struct {
	ID                   int32
	UserID               int64
	PaypalSubscriptionID string
	Starts               time.Time
	Ends                 time.Time
	IsManual             bool
	IsNotified           bool
	CreatedAt            pgtype.Timestamp
}

type OnlineUser struct {
	ID        int64
	Username  string
	FirstName string
	LastName  string
	IsBlocked pgtype.Bool
}
