// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO online.subscription (user_id, payment_ref, payment_token, starts, ends, is_manual)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, payment_ref, payment_token, starts, ends, is_manual, is_notified, is_active, created_at
`

type CreateSubscriptionParams struct {
	UserID       int64
	PaymentRef   string
	PaymentToken string
	Starts       time.Time
	Ends         time.Time
	IsManual     bool
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (OnlineSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PaymentRef,
		arg.PaymentToken,
		arg.Starts,
		arg.Ends,
		arg.IsManual,
	)
	var i OnlineSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentRef,
		&i.PaymentToken,
		&i.Starts,
		&i.Ends,
		&i.IsManual,
		&i.IsNotified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateSubscription = `-- name: DeactivateSubscription :exec
UPDATE online.subscription
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeactivateSubscription(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateSubscription, id)
	return err
}

const extendSubscription = `-- name: ExtendSubscription :exec
UPDATE online.subscription
SET ends = $2, is_notified = false
WHERE id = $1
`

type ExtendSubscriptionParams struct {
	ID   int32
	Ends time.Time
}

func (q *Queries) ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) error {
	_, err := q.db.Exec(ctx, extendSubscription, arg.ID, arg.Ends)
	return err
}

const findUsersByName = `-- name: FindUsersByName :many
SELECT id, username, first_name, last_name, is_blocked FROM online."user"
WHERE first_name ILIKE '%' || $1 || '%'
   OR last_name ILIKE '%' || $1 || '%'
   OR username ILIKE '%' || $1 || '%'
`

func (q *Queries) FindUsersByName(ctx context.Context, dollar_1 pgtype.Text) ([]OnlineUser, error) {
	rows, err := q.db.Query(ctx, findUsersByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnlineUser
	for rows.Next() {
		var i OnlineUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.IsBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, payment_ref, payment_token, starts, ends, is_manual, is_notified, is_active, created_at FROM online.subscription
WHERE user_id = $1 AND ends >= CURRENT_DATE
ORDER BY ends DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscription(ctx context.Context, userID int64) (OnlineSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, userID)
	var i OnlineSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentRef,
		&i.PaymentToken,
		&i.Starts,
		&i.Ends,
		&i.IsManual,
		&i.IsNotified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiredUsers = `-- name: GetExpiredUsers :many
SELECT u.id
FROM online."user" u
WHERE u.is_blocked = false
  AND NOT EXISTS (
    SELECT 1 FROM online.subscription s
    WHERE s.user_id = u.id AND s.ends >= CURRENT_DATE
  )
`

func (q *Queries) GetExpiredUsers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getExpiredUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManualSubscriptionsEndingTomorrow = `-- name: GetManualSubscriptionsEndingTomorrow :many
SELECT s.id, s.user_id, s.payment_ref, s.payment_token, s.starts, s.ends, s.is_manual, s.is_notified, s.is_active, s.created_at, u.username, u.first_name, u.last_name
FROM online.subscription s
JOIN online."user" u ON s.user_id = u.id
WHERE s.ends = CURRENT_DATE + 1
  AND s.is_notified = false
  AND s.is_manual = true
`

type GetManualSubscriptionsEndingTomorrowRow struct {
	ID           int32
	UserID       int64
	PaymentRef   string
	PaymentToken string
	Starts       time.Time
	Ends         time.Time
	IsManual     bool
	IsNotified   bool
	IsActive     bool
	CreatedAt    pgtype.Timestamp
	Username     string
	FirstName    string
	LastName     string
}

func (q *Queries) GetManualSubscriptionsEndingTomorrow(ctx context.Context) ([]GetManualSubscriptionsEndingTomorrowRow, error) {
	rows, err := q.db.Query(ctx, getManualSubscriptionsEndingTomorrow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManualSubscriptionsEndingTomorrowRow
	for rows.Next() {
		var i GetManualSubscriptionsEndingTomorrowRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentRef,
			&i.PaymentToken,
			&i.Starts,
			&i.Ends,
			&i.IsManual,
			&i.IsNotified,
			&i.IsActive,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByPaymentRef = `-- name: GetSubscriptionByPaymentRef :one
SELECT id, user_id, payment_ref, payment_token, starts, ends, is_manual, is_notified, is_active, created_at FROM online.subscription
WHERE payment_ref = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetSubscriptionByPaymentRef(ctx context.Context, paymentRef string) (OnlineSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByPaymentRef, paymentRef)
	var i OnlineSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentRef,
		&i.PaymentToken,
		&i.Starts,
		&i.Ends,
		&i.IsManual,
		&i.IsNotified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionsForRenewal = `-- name: GetSubscriptionsForRenewal :many
SELECT s.id, s.user_id, s.payment_ref, s.payment_token, s.starts, s.ends, s.is_manual, s.is_notified, s.is_active, s.created_at, u.username, u.first_name, u.last_name
FROM online.subscription s
JOIN online."user" u ON s.user_id = u.id
WHERE s.ends = CURRENT_DATE
  AND s.is_active = true
  AND s.is_manual = false
  AND s.payment_token <> ''
`

type GetSubscriptionsForRenewalRow struct {
	ID           int32
	UserID       int64
	PaymentRef   string
	PaymentToken string
	Starts       time.Time
	Ends         time.Time
	IsManual     bool
	IsNotified   bool
	IsActive     bool
	CreatedAt    pgtype.Timestamp
	Username     string
	FirstName    string
	LastName     string
}

func (q *Queries) GetSubscriptionsForRenewal(ctx context.Context) ([]GetSubscriptionsForRenewalRow, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsForRenewal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsForRenewalRow
	for rows.Next() {
		var i GetSubscriptionsForRenewalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentRef,
			&i.PaymentToken,
			&i.Starts,
			&i.Ends,
			&i.IsManual,
			&i.IsNotified,
			&i.IsActive,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, first_name, last_name, is_blocked FROM online."user" WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (OnlineUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i OnlineUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsBlocked,
	)
	return i, err
}

const markSubscriptionNotified = `-- name: MarkSubscriptionNotified :exec
UPDATE online.subscription
SET is_notified = true
WHERE id = $1
`

func (q *Queries) MarkSubscriptionNotified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markSubscriptionNotified, id)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO online."user" (id, username, first_name, last_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET username = EXCLUDED.username,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name
`

type UpsertUserParams struct {
	ID        int64
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
